### ISSUE TITLE
Position of step is top-left then it is hided.

### ISSUE THREAD

**Issue by quoctu2016** [miraxes/angular-custom-tour#14]
![image](https://user-images.githubusercontent.com/23717833/38244579-50dc56a0-3765-11e8-8244-8d291d742395.png)

**Comment by jitendra-tft** [comment]
position is not correct on fixed elements, it is possible to add custom style/css

**Comment by miraxes** [comment]
Yes it is possible. You can add customClasses and/or change default lib styling
