### ISSUE TITLE
selector already registered!

### ISSUE THREAD

**Issue by madurimanoj** [miraxes/angular-custom-tour#15]
here I'm highlighting the checkbox, it works fine for the first time. If I try to route to this page later, the following error pops in the console which doesn't allow the service call. Is there a way to unregister the selector after the tour. Thanks.
![image](https://user-images.githubusercontent.com/11791070/39128620-3a89189a-46d6-11e8-80de-68c163bc16f5.png)

**Comment by madurimanoj** [comment]
@miraxes thanks for your answer, it solves regarding highlighting the startAt(1) but not the _selector already registered_ error in console. This error is the blocker for other operations.

**Comment by madurimanoj** [comment]
@ritmittal2682 It won't work cause, it doesn't support for multiple components that's why he's suggesting to use `public startAt(stepId: number)` See --> Multiple Components support? #2 NO OFFENSE @miraxes  and Thanks.

**Comment by saurabhkjha** [comment]
I am using inside *ngIf - else , as soon as i toggle between template  the same error is coming like "selector already registered!"
