### ISSUE TITLE
Angular newest version support

### ISSUE THREAD

**Issue by guilhermejcgois** [miraxes/angular-custom-tour#17]
This lib supports Angular 5  6 7? I mean, in package.json the dependencies is locked to 4 version...

**Comment by miraxes** [comment]
Worked for me up to 6 version, didnt try on newest

**Comment by guilhermejcgois** [comment]
Make sense update versions on package.json file and move to peerDependencies?

**Comment by miraxes** [comment]
Sure, can you create PR for that? 🥇

**Comment by miraxes** [comment]
@guilhermejcgois  You can do it in one, just make sure it still supports older versions. Thanks.
