### ISSUE TITLE
Auto start not working

### ISSUE THREAD

**Issue by aimingxu** [miraxes/angular-custom-tour#5]
I want to auto start the tour after page load without click a button or link. Here is my code:
ngAfterContentInit(){
	setTimeout(function(){
            this.hintService.initialize();
}, 4000);
}
I got ERROR TypeError: Cannot read property 'initialize' of undefined.

**Comment by miraxes** [comment]
@aimingxu 
you just losing a *this* context . There are 2 ways to avoid it
1. bind this to some variable (old style)
`ngAfterContentInit(){
var self = this;
setTimeout(function(){
self.hintService.initialize();
}, 4000);
}`
2. And ES6 one is using lambda(arrow)
`ngAfterContentInit(){
setTimeout(() => {
this.hintService.initialize();
}, 4000);
}`

**Comment by miraxes** [comment]
@aimingxu 

Feels like solved, closing.
